In [30]:
import pandas as pd
import numpy as np

df_knn = pd.read_csv('KNN_resultados_FCLF.csv')
df_xgb = pd.read_csv('XGBoost_resultados_FCLF.csv')
df_ARIMA = pd.read_csv('ARIMA_resultados.csv')
df_RF = pd.read_csv('RF_resultados_FCLF.csv')
df_Lasso = pd.read_csv('Lasso_resultados_FCLF.csv')

In [31]:
df_knn = df_knn.drop(columns=["Unnamed: 0", "Overfitting?", "Underfitting?"])
df_knn = df_knn.rename(columns={
    'Real':'Valores Reais',
    'Previsto':'knn_Previsto',
    'Erro Absoluto':'knn_MAE',
    'Train RMSE':'knn_train_RMSE',
    'Test RMSE':'knn_test_RMSE'
        })

In [32]:
df_xgb = df_xgb.drop(columns=["Unnamed: 0", "Overfitting?", "Underfitting?"])
df_xgb = df_xgb.rename(columns={
    'Real':'Valores Reais',
    'Previsto':'xgb_Previsto',
    'Erro Absoluto':'xgb_MAE',
    'Train RMSE':'xgb_train_RMSE',
    'Test RMSE':'xgb_test_RMSE'
        })

In [33]:
df_ARIMA = df_ARIMA.drop(columns=["Unnamed: 0", "Overfitting?", "Underfitting?"])
df_ARIMA = df_ARIMA.rename(columns={
    'Real':'Valores Reais',
    'Previsto':'ARIMA_Previsto',
    'Erro Absoluto':'ARIMA_MAE',
    'Train RMSE':'ARIMA_train_RMSE',
    'Test RMSE':'ARIMA_test_RMSE'
        })

In [34]:
df_RF = df_RF.drop(columns=["Unnamed: 0", "Overfitting?", "Underfitting?"])
df_RF = df_RF.rename(columns={
    'Real':'Valores Reais',
    'Previsto':'RF_Previsto',
    'Erro Absoluto':'RF_MAE',
    'Train RMSE':'RF_train_RMSE',
    'Test RMSE':'RF_test_RMSE'
        })

In [35]:
df_Lasso = df_Lasso.drop(columns=["Unnamed: 0", "Overfitting?", "Underfitting?"])
df_Lasso = df_Lasso.rename(columns={
    'Real':'Valores Reais',
    'Previsto':'Lasso_Previsto',
    'Erro Absoluto':'Lasso_MAE',
    'Train RMSE':'Lasso_train_RMSE',
    'Test RMSE':'Lasso_test_RMSE'
        })

In [36]:
df = pd.merge(df_knn, df_xgb, on=['Empresa', 'Data', 'Valores Reais'], how='right')
df = pd.merge(df, df_ARIMA, on=['Empresa', 'Data', 'Valores Reais'], how='right')
df = pd.merge(df, df_RF, on=['Empresa', 'Data', 'Valores Reais'], how='right')
df = pd.merge(df, df_Lasso, on=['Empresa', 'Data', 'Valores Reais'], how='right')
df = df.dropna()
df

,Empresa,Data,Valores Reais,knn_Previsto,knn_MAE,knn_train_RMSE,knn_test_RMSE,xgb_Previsto,xgb_MAE,xgb_train_RMSE,...,ARIMA_train_RMSE,ARIMA_test_RMSE,RF_Previsto,RF_MAE,RF_train_RMSE,RF_test_RMSE,Lasso_Previsto,Lasso_MAE,Lasso_train_RMSE,Lasso_test_RMSE
0,3tentos,2022-10-01,0.377032,0.373997,0.003036,0.002873,0.003036,0.373997,0.003035,0.002873,...,0.004170,0.001882,0.373587,0.003445,0.002903,0.003445,0.373997,0.003036,0.002873,0.003036
1,3tentos,2023-01-01,0.376243,0.375915,0.000327,0.002505,0.000327,0.374604,0.001639,0.002842,...,0.003623,0.000413,0.374277,0.001965,0.002861,0.001965,0.374604,0.001639,0.002842,0.001639
2,3tentos,2023-04-01,0.375770,0.375986,0.000216,0.002290,0.000216,0.374877,0.000893,0.002666,...,0.003401,0.000286,0.374547,0.001223,0.002686,0.001223,0.374877,0.000893,0.002666,0.000893
3,3tentos,2023-07-01,0.377048,0.376452,0.000596,0.002109,0.000596,0.375004,0.002043,0.002488,...,0.003211,0.001330,0.374755,0.002293,0.002500,0.002293,0.375004,0.002043,0.002488,0.002043
4,3tentos,2023-10-01,0.375446,0.376523,0.001077,0.001975,0.001077,0.375260,0.000186,0.002423,...,0.002826,0.001456,0.375030,0.000416,0.002434,0.000416,0.375260,0.000186,0.002423,0.000186
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7921,Zamp S.A.,2023-07-01,0.377186,0.376602,0.000584,0.001216,0.000584,0.376214,0.000972,0.001629,...,0.002534,0.001062,0.376543,0.000643,0.001131,0.000643,0.376214,0.000972,0.001629,0.000972
7922,Zamp S.A.,2023-10-01,0.379456,0.377045,0.002411,0.001193,0.002411,0.376255,0.003202,0.001606,...,0.002489,0.002028,0.376429,0.003027,0.001103,0.003027,0.376255,0.003202,0.001606,0.003202
7923,Zamp S.A.,2024-01-01,0.372525,0.374952,0.002427,0.001222,0.002427,0.376383,0.003858,0.001694,...,0.002576,0.007685,0.375738,0.003213,0.001065,0.003213,0.376383,0.003858,0.001694,0.003858
7924,Zamp S.A.,2024-04-01,0.377701,0.377002,0.000699,0.001235,0.000699,0.376234,0.001467,0.001819,...,0.002711,0.005862,0.376906,0.000795,0.001167,0.000795,0.376234,0.001467,0.001819,0.001467
7925,Zamp S.A.,2024-07-01,0.374527,0.375345,0.000817,0.001216,0.000817,0.376289,0.001761,0.001807,...,0.002308,0.000892,0.375978,0.001451,0.001179,0.001451,0.376289,0.001761,0.001807,0.001761

In [37]:
from sklearn.metrics import mean_squared_error
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

# Função para calcular RMSE
def calcular_rmse_knn(df):
    return np.sqrt(mean_squared_error(df['Valores Reais'], df['knn_Previsto']))

# Aplicar por grupo (por empresa)
rmse_por_empresa_knn = df.groupby('Empresa').apply(calcular_rmse_knn).reset_index()
rmse_por_empresa_knn.columns = ['Empresa', 'RMSE_knn']

In [38]:
# Função para calcular RMSE
def calcular_rmse_xgb(df):
    return np.sqrt(mean_squared_error(df['Valores Reais'], df['xgb_Previsto']))

# Aplicar por grupo (por empresa)
rmse_por_empresa_xgb = df.groupby('Empresa').apply(calcular_rmse_xgb).reset_index()
rmse_por_empresa_xgb.columns = ['Empresa', 'RMSE_xgb']

In [39]:
# Função para calcular RMSE
def calcular_rmse_ARIMA(df):
    return np.sqrt(mean_squared_error(df['Valores Reais'], df['ARIMA_Previsto']))

# Aplicar por grupo (por empresa)
rmse_por_empresa_ARIMA = df.groupby('Empresa').apply(calcular_rmse_ARIMA).reset_index()
rmse_por_empresa_ARIMA.columns = ['Empresa', 'RMSE_ARIMA']

In [40]:
def calcular_rmse_RF(df):
    return np.sqrt(mean_squared_error(df['Valores Reais'], df['RF_Previsto']))

# Aplicar por grupo (por empresa)
rmse_por_empresa_RF = df.groupby('Empresa').apply(calcular_rmse_RF).reset_index()
rmse_por_empresa_RF.columns = ['Empresa', 'RMSE_RF']

In [41]:
def calcular_rmse_Lasso(df):
    return np.sqrt(mean_squared_error(df['Valores Reais'], df['Lasso_Previsto']))

# Aplicar por grupo (por empresa)
rmse_por_empresa_Lasso = df.groupby('Empresa').apply(calcular_rmse_Lasso).reset_index()
rmse_por_empresa_Lasso.columns = ['Empresa', 'RMSE_Lasso']

In [42]:
rmse_final = pd.merge(rmse_por_empresa_knn, rmse_por_empresa_xgb, on=['Empresa'], how='right')
rmse_final = pd.merge(rmse_final, rmse_por_empresa_ARIMA, on=['Empresa'], how='right')
rmse_final = pd.merge(rmse_final, rmse_por_empresa_RF, on=['Empresa'], how='right')
rmse_final = pd.merge(rmse_final, rmse_por_empresa_Lasso, on=['Empresa'], how='right')

empresa_maior_rmse_knn = rmse_final.loc[rmse_final['RMSE_knn'].idxmax()]
empresa_menor_rmse_knn = rmse_final.loc[rmse_final['RMSE_knn'].idxmin()]

# Maior e menor RMSE para o XGB
empresa_maior_rmse_xgb = rmse_final.loc[rmse_final['RMSE_xgb'].idxmax()]
empresa_menor_rmse_xgb = rmse_final.loc[rmse_final['RMSE_xgb'].idxmin()]

# Maior e menor RMSE para o ARIMA
empresa_maior_rmse_ARIMA = rmse_final.loc[rmse_final['RMSE_ARIMA'].idxmax()]
empresa_menor_rmse_ARIMA = rmse_final.loc[rmse_final['RMSE_ARIMA'].idxmin()]

# Maior e menor RMSE para o RF
empresa_maior_rmse_RF = rmse_final.loc[rmse_final['RMSE_RF'].idxmax()]
empresa_menor_rmse_RF = rmse_final.loc[rmse_final['RMSE_RF'].idxmin()]

# Maior e menor RMSE para o Lasso
empresa_maior_rmse_Lasso = rmse_final.loc[rmse_final['RMSE_Lasso'].idxmax()]
empresa_menor_rmse_Lasso = rmse_final.loc[rmse_final['RMSE_Lasso'].idxmin()]

print("Maior RMSE KNN:", empresa_maior_rmse_knn)
print("Menor RMSE KNN:", empresa_menor_rmse_knn)

print("Maior RMSE XGB:", empresa_maior_rmse_xgb)
print("Menor RMSE XGB:", empresa_menor_rmse_xgb)

print("Maior RMSE ARIMA:", empresa_maior_rmse_ARIMA)
print("Menor RMSE ARIMA:", empresa_menor_rmse_ARIMA)

print("Maior RMSE RF:", empresa_maior_rmse_RF)
print("Menor RMSE RF:", empresa_menor_rmse_RF)

print("Maior RMSE Lasso:", empresa_maior_rmse_Lasso)
print("Menor RMSE Lasso:", empresa_menor_rmse_Lasso)

Maior RMSE KNN: Empresa       Petrobras
RMSE_knn       0.134444
RMSE_xgb       0.189734
RMSE_ARIMA     0.211863
RMSE_RF        0.169591
RMSE_Lasso      0.23839
Name: 193, dtype: object
Menor RMSE KNN: Empresa       Recrusul
RMSE_knn      0.000003
RMSE_xgb      0.000003
RMSE_ARIMA    0.000011
RMSE_RF       0.000001
RMSE_Lasso    0.000003
Name: 210, dtype: object
Maior RMSE XGB: Empresa       Petrobras
RMSE_knn       0.134444
RMSE_xgb       0.189734
RMSE_ARIMA     0.211863
RMSE_RF        0.169591
RMSE_Lasso      0.23839
Name: 193, dtype: object
Menor RMSE XGB: Empresa       Recrusul
RMSE_knn      0.000003
RMSE_xgb      0.000003
RMSE_ARIMA    0.000011
RMSE_RF       0.000001
RMSE_Lasso    0.000003
Name: 210, dtype: object
Maior RMSE ARIMA: Empresa       Petrobras
RMSE_knn       0.134444
RMSE_xgb       0.189734
RMSE_ARIMA     0.211863
RMSE_RF        0.169591
RMSE_Lasso      0.23839
Name: 193, dtype: object
Menor RMSE ARIMA: Empresa       Dtcom Direct
RMSE_knn          0.000006
RMSE_xgb          0.000006
RMSE_ARIMA         0.00001
RMSE_RF           0.000006
RMSE_Lasso        0.000006
Name: 78, dtype: object
Maior RMSE RF: Empresa       Petrobras
RMSE_knn       0.134444
RMSE_xgb       0.189734
RMSE_ARIMA     0.211863
RMSE_RF        0.169591
RMSE_Lasso      0.23839
Name: 193, dtype: object
Menor RMSE RF: Empresa       Recrusul
RMSE_knn      0.000003
RMSE_xgb      0.000003
RMSE_ARIMA    0.000011
RMSE_RF       0.000001
RMSE_Lasso    0.000003
Name: 210, dtype: object
Maior RMSE Lasso: Empresa       Petrobras
RMSE_knn       0.134444
RMSE_xgb       0.189734
RMSE_ARIMA     0.211863
RMSE_RF        0.169591
RMSE_Lasso      0.23839
Name: 193, dtype: object
Menor RMSE Lasso: Empresa       Recrusul
RMSE_knn      0.000003
RMSE_xgb      0.000003
RMSE_ARIMA    0.000011
RMSE_RF       0.000001
RMSE_Lasso    0.000003
Name: 210, dtype: object

In [43]:
rmse_final.to_csv("rmse_final_FCLF.csv")

In [44]:
grupo = df.groupby('Empresa')[['knn_MAE', 'knn_train_RMSE', 'knn_test_RMSE', 'xgb_MAE', 'xgb_train_RMSE', 'xgb_test_RMSE', 'ARIMA_MAE', 'ARIMA_train_RMSE', 'ARIMA_test_RMSE', 'RF_MAE', 'RF_train_RMSE', 'RF_test_RMSE', 'Lasso_MAE', 'Lasso_train_RMSE', 'Lasso_test_RMSE']].mean().reset_index()
grupo #media do MAE, media do RMSE de treino e media do RMSE teste por modelo

,Empresa,knn_MAE,knn_train_RMSE,knn_test_RMSE,xgb_MAE,xgb_train_RMSE,xgb_test_RMSE,ARIMA_MAE,ARIMA_train_RMSE,ARIMA_test_RMSE,RF_MAE,RF_train_RMSE,RF_test_RMSE,Lasso_MAE,Lasso_train_RMSE,Lasso_test_RMSE
0,3tentos,0.001123,0.002088,0.001123,0.001658,0.002448,0.001658,0.001509,0.003086,0.001509,0.001798,0.002446,0.001798,0.001658,0.002448,0.001658
1,Aco Altona,0.000079,0.000071,0.000079,0.000080,0.000089,0.000080,0.000116,0.000143,0.000116,0.000070,0.000056,0.000070,0.000080,0.000089,0.000080
2,Aeris,0.001237,0.001563,0.001237,0.001757,0.002034,0.001757,0.001383,0.002247,0.001383,0.001694,0.001952,0.001694,0.001757,0.002034,0.001757
3,Afluente T,0.000080,0.000062,0.000080,0.000077,0.000075,0.000077,0.000122,0.000079,0.000122,0.000059,0.000049,0.000059,0.000077,0.000075,0.000077
4,Agrogalaxy,0.002183,0.001836,0.002183,0.003129,0.002751,0.003129,0.004518,0.003637,0.004518,0.003164,0.002767,0.003164,0.003129,0.002751,0.003129
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
275,Wilson Sons,0.000491,0.000292,0.000491,0.000598,0.000538,0.000598,0.000825,0.000698,0.000825,0.000481,0.000355,0.000481,0.000598,0.000538,0.000598
276,Wiz Co,0.001445,0.001258,0.001445,0.001504,0.001559,0.001504,0.002108,0.001828,0.002108,0.001439,0.001463,0.001439,0.001504,0.001559,0.001504
277,Wlm Ind Com,0.000053,0.000058,0.000053,0.000050,0.000066,0.000050,0.000056,0.000074,0.000056,0.000042,0.000048,0.000042,0.000050,0.000066,0.000050
278,Yduqs Part,0.001659,0.001784,0.001659,0.001941,0.002600,0.001941,0.002173,0.002830,0.002173,0.001614,0.001857,0.001614,0.001941,0.002600,0.001941
279,Zamp S.A.,0.000926,0.001546,0.000926,0.001311,0.001949,0.001311,0.002248,0.002857,0.002248,0.001185,0.001658,0.001185,0.001311,0.001949,0.001311

In [45]:
grupo.to_csv("friedman_data_FCLF.csv")

In [46]:
knn_MAE_media = df['knn_MAE'].mean()
knn_train_RMSE_media = df['knn_train_RMSE'].mean()
knn_test_RMSE_media = df['knn_test_RMSE'].mean()

xgb_MAE_media = df['xgb_MAE'].mean()
xgb_train_RMSE_media = df['xgb_train_RMSE'].mean()
xgb_test_RMSE_media = df['xgb_test_RMSE'].mean()

ARIMA_MAE_media = df['ARIMA_MAE'].mean()
ARIMA_train_RMSE_media = df['ARIMA_train_RMSE'].mean()
ARIMA_test_RMSE_media = df['ARIMA_test_RMSE'].mean()

RF_MAE_media = df['RF_MAE'].mean()
RF_train_RMSE_media = df['RF_train_RMSE'].mean()
RF_test_RMSE_media = df['RF_test_RMSE'].mean()

Lasso_MAE_media = df['Lasso_MAE'].mean()
Lasso_train_RMSE_media = df['Lasso_train_RMSE'].mean()
Lasso_test_RMSE_media = df['Lasso_test_RMSE'].mean()


print(f'MAE Médio KNN: {knn_MAE_media}') #é diferente do MAE geral do modelo pois as médias de cada empresas possuem ns diferentes (datasets com observações diferentes)
print(f'RMSE Treino Médio KNN: {knn_train_RMSE_media}')
print(f'RMSE Teste Médio KNN: {knn_test_RMSE_media}')

print(f'MAE Médio XGB: {xgb_MAE_media}')
print(f'RMSE Treino Médio XGB: {xgb_train_RMSE_media}')
print(f'RMSE Teste Médio XGB: {xgb_test_RMSE_media}')

print(f'MAE Médio ARIMA: {ARIMA_MAE_media}')
print(f'RMSE Treino Médio ARIMA: {ARIMA_train_RMSE_media}')
print(f'RMSE Teste Médio ARIMA: {ARIMA_test_RMSE_media}')

print(f'MAE Médio RF: {RF_MAE_media}')
print(f'RMSE Treino Médio RF: {RF_train_RMSE_media}')
print(f'RMSE Teste Médio RF: {RF_test_RMSE_media}')

print(f'MAE Médio Lasso: {Lasso_MAE_media}')
print(f'RMSE Treino Médio Lasso: {Lasso_train_RMSE_media}')
print(f'RMSE Teste Médio Lasso: {Lasso_test_RMSE_media}')

MAE Médio KNN: 0.0030233620713169223
RMSE Treino Médio KNN: 0.0025277417926999617
RMSE Teste Médio KNN: 0.0030233620713169223
MAE Médio XGB: 0.004133759728473713
RMSE Treino Médio XGB: 0.004245773647967615
RMSE Teste Médio XGB: 0.004133759728473713
MAE Médio ARIMA: 0.004869939761336072
RMSE Treino Médio ARIMA: 0.004805946898460361
RMSE Teste Médio ARIMA: 0.004869939761336072
MAE Médio RF: 0.003630575707968521
RMSE Treino Médio RF: 0.0031370859305613684
RMSE Teste Médio RF: 0.003630575707968521
MAE Médio Lasso: 0.0043487377211040975
RMSE Treino Médio Lasso: 0.004476334608242707
RMSE Teste Médio Lasso: 0.0043487377211040975

In [47]:
knn_MAE_std = df['knn_MAE'].std()
knn_train_RMSE_std = df['knn_train_RMSE'].std()
knn_test_RMSE_std = df['knn_test_RMSE'].std()

xgb_MAE_std = df['xgb_MAE'].std()
xgb_train_RMSE_std = df['xgb_train_RMSE'].std()
xgb_test_RMSE_std = df['xgb_test_RMSE'].std()

ARIMA_MAE_std = df['ARIMA_MAE'].std()
ARIMA_train_RMSE_std = df['ARIMA_train_RMSE'].std()
ARIMA_test_RMSE_std = df['ARIMA_test_RMSE'].std()

RF_MAE_std = df['RF_MAE'].std()
RF_train_RMSE_std = df['RF_train_RMSE'].std()
RF_test_RMSE_std = df['RF_test_RMSE'].std()

Lasso_MAE_std = df['Lasso_MAE'].std()
Lasso_train_RMSE_std = df['Lasso_train_RMSE'].std()
Lasso_test_RMSE_std = df['Lasso_test_RMSE'].std()

print(f'MAE Std KNN: {knn_MAE_std}') #é diferente do MAE geral do modelo pois as médias de cada empresas possuem ns diferentes (datasets com observações diferentes)
print(f'RMSE Treino Std KNN: {knn_train_RMSE_std}')
print(f'RMSE Teste Std KNN: {knn_test_RMSE_std}')

print(f'MAE Std XGB: {xgb_MAE_std}')
print(f'RMSE Treino Std XGB: {xgb_train_RMSE_std}')
print(f'RMSE Teste Std XGB: {xgb_test_RMSE_std}')

print(f'MAE Std ARIMA: {ARIMA_MAE_std}')
print(f'RMSE Treino Std ARIMA: {ARIMA_train_RMSE_std}')
print(f'RMSE Teste Std ARIMA: {ARIMA_test_RMSE_std}')

print(f'MAE Std RF: {RF_MAE_std}')
print(f'RMSE Treino Std RF: {RF_train_RMSE_std}')
print(f'RMSE Teste Std RF: {RF_test_RMSE_std}')

print(f'MAE Std Lasso: {Lasso_MAE_std}')
print(f'RMSE Treino Std Lasso: {Lasso_train_RMSE_std}')
print(f'RMSE Teste Std Lasso: {Lasso_test_RMSE_std}')

MAE Std KNN: 0.01307555417649213
RMSE Treino Std KNN: 0.006928784355001896
RMSE Teste Std KNN: 0.01307555417649213
MAE Std XGB: 0.017412024267439236
RMSE Treino Std XGB: 0.011248661917606853
RMSE Teste Std XGB: 0.017412024267439236
MAE Std ARIMA: 0.01959229660489509
RMSE Treino Std ARIMA: 0.01406869190455218
RMSE Teste Std ARIMA: 0.01959229660489509
MAE Std RF: 0.015599759507598883
RMSE Treino Std RF: 0.008835670907010445
RMSE Teste Std RF: 0.015599759507598883
MAE Std Lasso: 0.02018252202349834
RMSE Treino Std Lasso: 0.01416216906924839
RMSE Teste Std Lasso: 0.02018252202349834

In [48]:
from scipy.stats import friedmanchisquare
from scipy.stats import rankdata
import scikit_posthocs as sp

friedman_MAE = friedmanchisquare(grupo['knn_MAE'], grupo['xgb_MAE'], grupo['ARIMA_MAE'], grupo['RF_MAE'], grupo['Lasso_MAE']) 

friedman_MAE

FriedmanchisquareResult(statistic=533.5962843872815, pvalue=3.621150900496473e-114)

In [49]:
metric_cols = ['knn_MAE', 'xgb_MAE', 'ARIMA_MAE', 'RF_MAE', 'Lasso_MAE']   
model_names = ['KNN', 'XGB', 'ARIMA', 'RF', 'Lasso']

df_sp_MAE = grupo[metric_cols]
df_sp_MAE.columns = model_names

df_sp_MAE_long = df_sp_MAE.melt(var_name='Modelo', value_name='MAE')

dunn_MAE = sp.posthoc_dunn(df_sp_MAE_long, group_col='Modelo', val_col='MAE', p_adjust='bonferroni')
dunn_MAE

          ARIMA       KNN     Lasso        RF       XGB
ARIMA  1.000000  0.015933  1.000000  0.556561  1.000000
KNN    0.015933  1.000000  0.495671  1.000000  0.498102
Lasso  1.000000  0.495671  1.000000  1.000000  1.000000
RF     0.556561  1.000000  1.000000  1.000000  1.000000
XGB    1.000000  0.498102  1.000000  1.000000  1.000000

In [50]:
# Aplicar ranking por linha (menor MAE = melhor)
ranks_MAE = grupo[['knn_MAE', 'xgb_MAE', 'ARIMA_MAE', 'RF_MAE', 'Lasso_MAE']].apply(rankdata, axis=1)
mean_ranks_MAE = ranks_MAE.mean(axis=0)

# Exibir ranking médio
print("Rank médio da MAE dos modelos:")
for i, rank in enumerate(mean_ranks_MAE, start=1):
    print(f"Modelo {i}: {rank:.3f}")

Rank médio da MAE dos modelos:
Modelo 1: 1.796
Modelo 2: 3.261
Modelo 3: 4.518
Modelo 4: 2.089
Modelo 5: 3.336

In [51]:
friedman_RMSE_train = friedmanchisquare(grupo['knn_train_RMSE'], grupo['xgb_train_RMSE'], grupo['ARIMA_train_RMSE'], grupo['RF_train_RMSE'], grupo['Lasso_train_RMSE']) 

friedman_RMSE_train

FriedmanchisquareResult(statistic=966.1789605286662, pvalue=7.617809373973411e-208)

In [52]:
metric_cols = ['knn_train_RMSE', 'xgb_train_RMSE', 'ARIMA_train_RMSE', 'RF_train_RMSE', 'Lasso_train_RMSE']   
model_names = ['KNN', 'XGB', 'ARIMA', 'RF', 'Lasso']

df_sp_RMSE = grupo[metric_cols]
df_sp_RMSE.columns = model_names

df_sp_RMSE_long = df_sp_RMSE.melt(var_name='Modelo', value_name='RMSE')

dunn_RMSE = sp.posthoc_dunn(df_sp_RMSE_long, group_col='Modelo', val_col='RMSE', p_adjust='bonferroni')
dunn_RMSE

          ARIMA       KNN     Lasso        RF       XGB
ARIMA  1.000000  0.000016  1.000000  0.005643  1.000000
KNN    0.000016  1.000000  0.014463  1.000000  0.013083
Lasso  1.000000  0.014463  1.000000  0.664032  1.000000
RF     0.005643  1.000000  0.664032  1.000000  0.622385
XGB    1.000000  0.013083  1.000000  0.622385  1.000000

In [53]:
# Aplicar ranking por linha (menor MAE = melhor)r
ranks_RMSE_train = grupo[['knn_train_RMSE', 'xgb_train_RMSE', 'ARIMA_train_RMSE', 'RF_train_RMSE', 'Lasso_train_RMSE']].apply(rankdata, axis=1)
mean_ranks_RMSE_train = ranks_RMSE_train.mean(axis=0)

# Exibir ranking médio
print("Rank médio da RMSE do treino dos modelos:")
for i, rank in enumerate(mean_ranks_RMSE_train, start=1):
    print(f"Modelo {i}: {rank:.3f}")

Rank médio da RMSE do treino dos modelos:
Modelo 1: 1.234
Modelo 2: 3.961
Modelo 3: 4.871
Modelo 4: 1.961
Modelo 5: 2.973

In [54]:
rmse_final

         Empresa  RMSE_knn  RMSE_xgb  RMSE_ARIMA   RMSE_RF  RMSE_Lasso
0        3tentos  0.001531  0.001866    0.001784  0.002006    0.001866
1     Aco Altona  0.000119  0.000119    0.000157  0.000106    0.000119
2          Aeris  0.001411  0.001978    0.001605  0.001912    0.001978
3     Afluente T  0.000104  0.000103    0.000176  0.000083    0.000103
4     Agrogalaxy  0.002752  0.003606    0.004989  0.003588    0.003606
..           ...       ...       ...         ...       ...         ...
275  Wilson Sons  0.000677  0.000781    0.001019  0.000636    0.000781
276       Wiz Co  0.001983  0.002075    0.002896  0.002030    0.002075
277  Wlm Ind Com  0.000077  0.000070    0.000079  0.000064    0.000070
278   Yduqs Part  0.002487  0.002904    0.002947  0.002662    0.002904
279    Zamp S.A.  0.001276  0.001639    0.003084  0.001498    0.001639

[280 rows x 6 columns]

In [55]:
friedman_RMSE = friedmanchisquare(rmse_final['RMSE_knn'], rmse_final['RMSE_xgb'], rmse_final['RMSE_ARIMA'], rmse_final['RMSE_RF'], rmse_final['RMSE_Lasso']) 

friedman_RMSE

FriedmanchisquareResult(statistic=560.8202929617719, pvalue=4.6640206640264916e-120)

In [56]:
# Aplicar ranking por linha (menor MAE = melhor)r
ranks_RMSE = rmse_final[['RMSE_knn', 'RMSE_xgb', 'RMSE_ARIMA', 'RMSE_RF', 'RMSE_Lasso']].apply(rankdata, axis=1)
mean_ranks_RMSE = ranks_RMSE.mean(axis=0)

# Exibir ranking médio
print("Rank médio da RMSE geral dos modelos:")
for i, rank in enumerate(mean_ranks_RMSE, start=1):
    print(f"Modelo {i}: {rank:.3f}")

Rank médio da RMSE geral dos modelos:
Modelo 1: 1.754
Modelo 2: 3.200
Modelo 3: 4.600
Modelo 4: 2.132
Modelo 5: 3.314

In [57]:
rmse_final

         Empresa  RMSE_knn  RMSE_xgb  RMSE_ARIMA   RMSE_RF  RMSE_Lasso
0        3tentos  0.001531  0.001866    0.001784  0.002006    0.001866
1     Aco Altona  0.000119  0.000119    0.000157  0.000106    0.000119
2          Aeris  0.001411  0.001978    0.001605  0.001912    0.001978
3     Afluente T  0.000104  0.000103    0.000176  0.000083    0.000103
4     Agrogalaxy  0.002752  0.003606    0.004989  0.003588    0.003606
..           ...       ...       ...         ...       ...         ...
275  Wilson Sons  0.000677  0.000781    0.001019  0.000636    0.000781
276       Wiz Co  0.001983  0.002075    0.002896  0.002030    0.002075
277  Wlm Ind Com  0.000077  0.000070    0.000079  0.000064    0.000070
278   Yduqs Part  0.002487  0.002904    0.002947  0.002662    0.002904
279    Zamp S.A.  0.001276  0.001639    0.003084  0.001498    0.001639

[280 rows x 6 columns]