In [8]:
import pandas as pd
import numpy as np

df_knn = pd.read_csv('KNN_resultados_FCLF_AT.csv')
df_xgb = pd.read_csv('XGBoost_resultados_FCLF_AT.csv')
df_ARIMA = pd.read_csv('ARIMA_resultados_FCLF_AT.csv')
df_RF = pd.read_csv('RF_resultados_FCLF_AT.csv')
df_Lasso = pd.read_csv('Lasso_resultados_FCLF_AT.csv')

In [9]:
df_knn = df_knn.drop(columns=["Unnamed: 0", "Overfitting?", "Underfitting?"])
df_knn = df_knn.rename(columns={
    'Real':'Valores Reais',
    'Previsto':'knn_Previsto',
    'Erro Absoluto':'knn_MAE',
    'Train RMSE':'knn_train_RMSE',
    'Test RMSE':'knn_test_RMSE'
        })

In [10]:
df_xgb = df_xgb.drop(columns=["Unnamed: 0", "Overfitting?", "Underfitting?"])
df_xgb = df_xgb.rename(columns={
    'Real':'Valores Reais',
    'Previsto':'xgb_Previsto',
    'Erro Absoluto':'xgb_MAE',
    'Train RMSE':'xgb_train_RMSE',
    'Test RMSE':'xgb_test_RMSE'
        })

In [11]:
df_ARIMA = df_ARIMA.drop(columns=["Unnamed: 0", "Overfitting?", "Underfitting?"])
df_ARIMA = df_ARIMA.rename(columns={
    'Real':'Valores Reais',
    'Previsto':'ARIMA_Previsto',
    'Erro Absoluto':'ARIMA_MAE',
    'Train RMSE':'ARIMA_train_RMSE',
    'Test RMSE':'ARIMA_test_RMSE'
        })

In [12]:
df_RF = df_RF.drop(columns=["Unnamed: 0", "Overfitting?", "Underfitting?"])
df_RF = df_RF.rename(columns={
    'Real':'Valores Reais',
    'Previsto':'RF_Previsto',
    'Erro Absoluto':'RF_MAE',
    'Train RMSE':'RF_train_RMSE',
    'Test RMSE':'RF_test_RMSE'
        })

In [13]:
df_Lasso = df_Lasso.drop(columns=["Unnamed: 0", "Overfitting?", "Underfitting?"])
df_Lasso = df_Lasso.rename(columns={
    'Real':'Valores Reais',
    'Previsto':'Lasso_Previsto',
    'Erro Absoluto':'Lasso_MAE',
    'Train RMSE':'Lasso_train_RMSE',
    'Test RMSE':'Lasso_test_RMSE'
        })

In [14]:
df = pd.merge(df_knn, df_xgb, on=['Empresa', 'Data', 'Valores Reais'], how='right')
df = pd.merge(df, df_ARIMA, on=['Empresa', 'Data', 'Valores Reais'], how='right')
df = pd.merge(df, df_RF, on=['Empresa', 'Data', 'Valores Reais'], how='right')
df = pd.merge(df, df_Lasso, on=['Empresa', 'Data', 'Valores Reais'], how='right')
df = df.dropna()
df

,Empresa,Data,Valores Reais,knn_Previsto,knn_MAE,knn_train_RMSE,knn_test_RMSE,xgb_Previsto,xgb_MAE,xgb_train_RMSE,...,ARIMA_train_RMSE,ARIMA_test_RMSE,RF_Previsto,RF_MAE,RF_train_RMSE,RF_test_RMSE,Lasso_Previsto,Lasso_MAE,Lasso_train_RMSE,Lasso_test_RMSE
0,3tentos,2022-12-31,0.421361,0.419383,0.001978,0.002307,0.001978,0.419383,0.001978,0.002307,...,0.003342,0.001682,0.419540,0.001821,0.002312,0.001821,0.419383,0.001978,0.002307,0.001978
1,3tentos,2023-03-31,0.420493,0.420760,0.000266,0.002484,0.000266,0.419778,0.000715,0.002210,...,0.002957,0.001393,0.420029,0.000464,0.002224,0.000464,0.419778,0.000715,0.002210,0.000715
2,3tentos,2023-06-30,0.421027,0.420588,0.000440,0.002174,0.000440,0.419898,0.001130,0.002035,...,0.004757,0.000762,0.420138,0.000889,0.002049,0.000889,0.419898,0.001130,0.002035,0.001130
3,3tentos,2023-09-30,0.421904,0.421140,0.000764,0.001935,0.000764,0.420059,0.001845,0.001925,...,0.002466,0.001329,0.420236,0.001668,0.001933,0.001668,0.420059,0.001845,0.001925,0.001845
4,3tentos,2023-12-31,0.421117,0.420198,0.000918,0.001826,0.000918,0.420290,0.000827,0.001901,...,0.002440,0.000699,0.420444,0.000673,0.001907,0.000673,0.420289,0.000827,0.001901,0.000827
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14451,Zamp S.A.,2023-12-31,0.421693,0.421412,0.000282,0.001009,0.000282,0.420768,0.000925,0.001167,...,0.001325,0.000513,0.420914,0.000779,0.000534,0.000779,0.420768,0.000925,0.001167,0.000925
14452,Zamp S.A.,2024-03-31,0.418155,0.420862,0.002707,0.000990,0.002707,0.420802,0.002647,0.001159,...,0.001303,0.003153,0.419869,0.001715,0.000546,0.001715,0.420802,0.002647,0.001159,0.002647
14453,Zamp S.A.,2024-06-30,0.422870,0.421518,0.001352,0.001039,0.001352,0.420708,0.002162,0.001240,...,0.001398,0.001853,0.421417,0.001453,0.000521,0.001453,0.420708,0.002162,0.001240,0.002162
14454,Zamp S.A.,2024-09-30,0.419901,0.421076,0.001176,0.001038,0.001176,0.420782,0.000882,0.001280,...,0.001383,0.000684,0.420433,0.000533,0.000514,0.000533,0.420782,0.000882,0.001280,0.000882
14455,Zamp S.A.,2024-12-31,0.421989,0.421513,0.000476,0.001026,0.000476,0.420753,0.001236,0.001269,...,0.001362,0.000813,0.420899,0.001090,0.000513,0.001090,0.420753,0.001236,0.001269,0.001236

In [15]:
from sklearn.metrics import mean_squared_error
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

# Função para calcular RMSE
def calcular_rmse_knn(df):
    return np.sqrt(mean_squared_error(df['Valores Reais'], df['knn_Previsto']))

# Aplicar por grupo (por empresa)
rmse_por_empresa_knn = df.groupby('Empresa').apply(calcular_rmse_knn).reset_index()
rmse_por_empresa_knn.columns = ['Empresa', 'RMSE_knn']

In [16]:
# Função para calcular RMSE
def calcular_rmse_xgb(df):
    return np.sqrt(mean_squared_error(df['Valores Reais'], df['xgb_Previsto']))

# Aplicar por grupo (por empresa)
rmse_por_empresa_xgb = df.groupby('Empresa').apply(calcular_rmse_xgb).reset_index()
rmse_por_empresa_xgb.columns = ['Empresa', 'RMSE_xgb']

In [17]:
# Função para calcular RMSE
def calcular_rmse_ARIMA(df):
    return np.sqrt(mean_squared_error(df['Valores Reais'], df['ARIMA_Previsto']))

# Aplicar por grupo (por empresa)
rmse_por_empresa_ARIMA = df.groupby('Empresa').apply(calcular_rmse_ARIMA).reset_index()
rmse_por_empresa_ARIMA.columns = ['Empresa', 'RMSE_ARIMA']

In [18]:
def calcular_rmse_RF(df):
    return np.sqrt(mean_squared_error(df['Valores Reais'], df['RF_Previsto']))

# Aplicar por grupo (por empresa)
rmse_por_empresa_RF = df.groupby('Empresa').apply(calcular_rmse_RF).reset_index()
rmse_por_empresa_RF.columns = ['Empresa', 'RMSE_RF']

In [19]:
def calcular_rmse_Lasso(df):
    return np.sqrt(mean_squared_error(df['Valores Reais'], df['Lasso_Previsto']))

# Aplicar por grupo (por empresa)
rmse_por_empresa_Lasso = df.groupby('Empresa').apply(calcular_rmse_Lasso).reset_index()
rmse_por_empresa_Lasso.columns = ['Empresa', 'RMSE_Lasso']

In [20]:
rmse_final = pd.merge(rmse_por_empresa_knn, rmse_por_empresa_xgb, on=['Empresa'], how='right')
rmse_final = pd.merge(rmse_final, rmse_por_empresa_ARIMA, on=['Empresa'], how='right')
rmse_final = pd.merge(rmse_final, rmse_por_empresa_RF, on=['Empresa'], how='right')
rmse_final = pd.merge(rmse_final, rmse_por_empresa_Lasso, on=['Empresa'], how='right')

empresa_maior_rmse_knn = rmse_final.loc[rmse_final['RMSE_knn'].idxmax()]
empresa_menor_rmse_knn = rmse_final.loc[rmse_final['RMSE_knn'].idxmin()]

# Maior e menor RMSE para o XGB
empresa_maior_rmse_xgb = rmse_final.loc[rmse_final['RMSE_xgb'].idxmax()]
empresa_menor_rmse_xgb = rmse_final.loc[rmse_final['RMSE_xgb'].idxmin()]

# Maior e menor RMSE para o ARIMA
empresa_maior_rmse_ARIMA = rmse_final.loc[rmse_final['RMSE_ARIMA'].idxmax()]
empresa_menor_rmse_ARIMA = rmse_final.loc[rmse_final['RMSE_ARIMA'].idxmin()]

# Maior e menor RMSE para o RF
empresa_maior_rmse_RF = rmse_final.loc[rmse_final['RMSE_RF'].idxmax()]
empresa_menor_rmse_RF = rmse_final.loc[rmse_final['RMSE_RF'].idxmin()]

# Maior e menor RMSE para o Lasso
empresa_maior_rmse_Lasso = rmse_final.loc[rmse_final['RMSE_Lasso'].idxmax()]
empresa_menor_rmse_Lasso = rmse_final.loc[rmse_final['RMSE_Lasso'].idxmin()]

print("Maior RMSE KNN:", empresa_maior_rmse_knn)
print("Menor RMSE KNN:", empresa_menor_rmse_knn)

print("Maior RMSE XGB:", empresa_maior_rmse_xgb)
print("Menor RMSE XGB:", empresa_menor_rmse_xgb)

print("Maior RMSE ARIMA:", empresa_maior_rmse_ARIMA)
print("Menor RMSE ARIMA:", empresa_menor_rmse_ARIMA)

print("Maior RMSE RF:", empresa_maior_rmse_RF)
print("Menor RMSE RF:", empresa_menor_rmse_RF)

print("Maior RMSE Lasso:", empresa_maior_rmse_Lasso)
print("Menor RMSE Lasso:", empresa_menor_rmse_Lasso)

Maior RMSE KNN: Empresa         Raizen
RMSE_knn      0.093667
RMSE_xgb      0.107366
RMSE_ARIMA    0.194624
RMSE_RF       0.104684
RMSE_Lasso    0.107366
Name: 352, dtype: object
Menor RMSE KNN: Empresa       Caconde Part
RMSE_knn               0.0
RMSE_xgb               0.0
RMSE_ARIMA             0.0
RMSE_RF                0.0
RMSE_Lasso             0.0
Name: 80, dtype: object
Maior RMSE XGB: Empresa       Petrobras
RMSE_knn       0.089133
RMSE_xgb       0.144013
RMSE_ARIMA     0.160114
RMSE_RF        0.124281
RMSE_Lasso     0.167751
Name: 329, dtype: object
Menor RMSE XGB: Empresa       Caconde Part
RMSE_knn               0.0
RMSE_xgb               0.0
RMSE_ARIMA             0.0
RMSE_RF                0.0
RMSE_Lasso             0.0
Name: 80, dtype: object
Maior RMSE ARIMA: Empresa         Raizen
RMSE_knn      0.093667
RMSE_xgb      0.107366
RMSE_ARIMA    0.194624
RMSE_RF       0.104684
RMSE_Lasso    0.107366
Name: 352, dtype: object
Menor RMSE ARIMA: Empresa       Caianda Part
RMSE_knn               0.0
RMSE_xgb               0.0
RMSE_ARIMA             0.0
RMSE_RF                0.0
RMSE_Lasso             0.0
Name: 81, dtype: object
Maior RMSE RF: Empresa       Petrobras
RMSE_knn       0.089133
RMSE_xgb       0.144013
RMSE_ARIMA     0.160114
RMSE_RF        0.124281
RMSE_Lasso     0.167751
Name: 329, dtype: object
Menor RMSE RF: Empresa       Caconde Part
RMSE_knn               0.0
RMSE_xgb               0.0
RMSE_ARIMA             0.0
RMSE_RF                0.0
RMSE_Lasso             0.0
Name: 80, dtype: object
Maior RMSE Lasso: Empresa       Petrobras
RMSE_knn       0.089133
RMSE_xgb       0.144013
RMSE_ARIMA     0.160114
RMSE_RF        0.124281
RMSE_Lasso     0.167751
Name: 329, dtype: object
Menor RMSE Lasso: Empresa       Caconde Part
RMSE_knn               0.0
RMSE_xgb               0.0
RMSE_ARIMA             0.0
RMSE_RF                0.0
RMSE_Lasso             0.0
Name: 80, dtype: object

In [21]:
rmse_final.to_csv("rmse_final_FCLF_AT.csv")

In [22]:
grupo = df.groupby('Empresa')[['knn_MAE', 'knn_train_RMSE', 'knn_test_RMSE', 'xgb_MAE', 'xgb_train_RMSE', 'xgb_test_RMSE', 'ARIMA_MAE', 'ARIMA_train_RMSE', 'ARIMA_test_RMSE', 'RF_MAE', 'RF_train_RMSE', 'RF_test_RMSE', 'Lasso_MAE', 'Lasso_train_RMSE', 'Lasso_test_RMSE']].mean().reset_index()
grupo #media do MAE, media do RMSE de treino e media do RMSE teste por modelo

,Empresa,knn_MAE,knn_train_RMSE,knn_test_RMSE,xgb_MAE,xgb_train_RMSE,xgb_test_RMSE,ARIMA_MAE,ARIMA_train_RMSE,ARIMA_test_RMSE,RF_MAE,RF_train_RMSE,RF_test_RMSE,Lasso_MAE,Lasso_train_RMSE,Lasso_test_RMSE
0,3tentos,9.382494e-04,1.926887e-03,9.382494e-04,1.244637e-03,1.915516e-03,1.244637e-03,1.270217e-03,2.704505e-03,1.270217e-03,1.119002e-03,1.912306e-03,1.119002e-03,1.244645e-03,1.915516e-03,1.244645e-03
1,521 Particip,2.134757e-03,3.369389e-03,2.134757e-03,2.099006e-03,3.694601e-03,2.099006e-03,2.887249e-03,4.414834e-03,2.887249e-03,2.032699e-03,3.403346e-03,2.032699e-03,2.099009e-03,3.694601e-03,2.099009e-03
2,524 Particip,1.858486e-07,2.304660e-07,1.858486e-07,1.775911e-07,2.348161e-07,1.775911e-07,4.456394e-07,3.363164e-07,4.456394e-07,1.770397e-07,2.348770e-07,1.770397e-07,1.785077e-07,2.346461e-07,1.785077e-07
3,AES Brasil,2.422142e-03,1.474042e-03,2.422142e-03,2.819843e-03,2.902862e-03,2.819843e-03,2.958287e-03,3.216160e-03,2.958287e-03,1.885284e-03,1.703508e-03,1.885284e-03,2.819844e-03,2.902862e-03,2.819844e-03
4,AES Elpa,1.559401e-03,1.100086e-03,1.559401e-03,1.659501e-03,1.611211e-03,1.659501e-03,2.002930e-03,1.892373e-03,2.002930e-03,1.388347e-03,1.202497e-03,1.388347e-03,1.659502e-03,1.611211e-03,1.659502e-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
466,Yara Brasil,9.368899e-04,3.085090e-03,9.368899e-04,1.703983e-03,3.205578e-03,1.703983e-03,2.039568e-04,4.133911e-03,2.039568e-04,2.146582e-03,3.238148e-03,2.146582e-03,1.703987e-03,3.205578e-03,1.703987e-03
467,Ybyra S/A,1.984084e-05,1.218723e-06,1.984084e-05,2.010510e-05,1.527757e-06,2.010510e-05,2.432949e-05,1.885780e-06,2.432949e-05,1.996930e-05,1.062412e-06,1.996930e-05,2.010339e-05,1.527629e-06,2.010339e-05
468,Yduqs Part,1.401451e-03,1.019401e-03,1.401451e-03,1.333301e-03,1.334706e-03,1.333301e-03,1.456787e-03,1.459292e-03,1.456787e-03,9.719935e-04,6.652065e-04,9.719935e-04,1.333301e-03,1.334706e-03,1.333301e-03
469,Zain Part,3.884825e-08,2.084440e-08,3.884825e-08,3.682718e-08,2.094215e-08,3.682718e-08,6.446388e-08,4.908123e-08,6.446388e-08,4.018180e-08,2.088701e-08,4.018180e-08,3.884825e-08,2.084440e-08,3.884825e-08
470,Zamp S.A.,1.083857e-03,1.234802e-03,1.083857e-03,1.040639e-03,1.390792e-03,1.040639e-03,1.105399e-03,1.739807e-03,1.105399e-03,8.303352e-04,1.012208e-03,8.303352e-04,1.040640e-03,1.390792e-03,1.040640e-03

In [24]:
knn_MAE_media = df['knn_MAE'].mean()
knn_train_RMSE_media = df['knn_train_RMSE'].mean()
knn_test_RMSE_media = df['knn_test_RMSE'].mean()

xgb_MAE_media = df['xgb_MAE'].mean()
xgb_train_RMSE_media = df['xgb_train_RMSE'].mean()
xgb_test_RMSE_media = df['xgb_test_RMSE'].mean()

ARIMA_MAE_media = df['ARIMA_MAE'].mean()
ARIMA_train_RMSE_media = df['ARIMA_train_RMSE'].mean()
ARIMA_test_RMSE_media = df['ARIMA_test_RMSE'].mean()

RF_MAE_media = df['RF_MAE'].mean()
RF_train_RMSE_media = df['RF_train_RMSE'].mean()
RF_test_RMSE_media = df['RF_test_RMSE'].mean()

Lasso_MAE_media = df['Lasso_MAE'].mean()
Lasso_train_RMSE_media = df['Lasso_train_RMSE'].mean()
Lasso_test_RMSE_media = df['Lasso_test_RMSE'].mean()


print(f'MAE Médio KNN: {knn_MAE_media}') #é diferente do MAE geral do modelo pois as médias de cada empresas possuem ns diferentes (datasets com observações diferentes)
print(f'RMSE Treino Médio KNN: {knn_train_RMSE_media}')
print(f'RMSE Teste Médio KNN: {knn_test_RMSE_media}')

print(f'MAE Médio XGB: {xgb_MAE_media}')
print(f'RMSE Treino Médio XGB: {xgb_train_RMSE_media}')
print(f'RMSE Teste Médio XGB: {xgb_test_RMSE_media}')

print(f'MAE Médio ARIMA: {ARIMA_MAE_media}')
print(f'RMSE Treino Médio ARIMA: {ARIMA_train_RMSE_media}')
print(f'RMSE Teste Médio ARIMA: {ARIMA_test_RMSE_media}')

print(f'MAE Médio RF: {RF_MAE_media}')
print(f'RMSE Treino Médio RF: {RF_train_RMSE_media}')
print(f'RMSE Teste Médio RF: {RF_test_RMSE_media}')

print(f'MAE Médio Lasso: {Lasso_MAE_media}')
print(f'RMSE Treino Médio Lasso: {Lasso_train_RMSE_media}')
print(f'RMSE Teste Médio Lasso: {Lasso_test_RMSE_media}')

MAE Médio KNN: 0.0023642785926189795
RMSE Treino Médio KNN: 0.002489436233605667
RMSE Teste Médio KNN: 0.0023642785926189795
MAE Médio XGB: 0.0031337733860289175
RMSE Treino Médio XGB: 0.0038760556865609147
RMSE Teste Médio XGB: 0.0031337733860289175
MAE Médio ARIMA: 0.0036595173317065005
RMSE Treino Médio ARIMA: 0.004382739732635755
RMSE Teste Médio ARIMA: 0.0036595173317065005
MAE Médio RF: 0.002524854382080744
RMSE Treino Médio RF: 0.002625517033347005
RMSE Teste Médio RF: 0.002524854382080744
MAE Médio Lasso: 0.003230380173875231
RMSE Treino Médio Lasso: 0.003956630692885007
RMSE Teste Médio Lasso: 0.003230380173875231

In [25]:
knn_MAE_std = df['knn_MAE'].std()
knn_train_RMSE_std = df['knn_train_RMSE'].std()
knn_test_RMSE_std = df['knn_test_RMSE'].std()

xgb_MAE_std = df['xgb_MAE'].std()
xgb_train_RMSE_std = df['xgb_train_RMSE'].std()
xgb_test_RMSE_std = df['xgb_test_RMSE'].std()

ARIMA_MAE_std = df['ARIMA_MAE'].std()
ARIMA_train_RMSE_std = df['ARIMA_train_RMSE'].std()
ARIMA_test_RMSE_std = df['ARIMA_test_RMSE'].std()

RF_MAE_std = df['RF_MAE'].std()
RF_train_RMSE_std = df['RF_train_RMSE'].std()
RF_test_RMSE_std = df['RF_test_RMSE'].std()

Lasso_MAE_std = df['Lasso_MAE'].std()
Lasso_train_RMSE_std = df['Lasso_train_RMSE'].std()
Lasso_test_RMSE_std = df['Lasso_test_RMSE'].std()

print(f'MAE Std KNN: {knn_MAE_std}') #é diferente do MAE geral do modelo pois as médias de cada empresas possuem ns diferentes (datasets com observações diferentes)
print(f'RMSE Treino Std KNN: {knn_train_RMSE_std}')
print(f'RMSE Teste Std KNN: {knn_test_RMSE_std}')

print(f'MAE Std XGB: {xgb_MAE_std}')
print(f'RMSE Treino Std XGB: {xgb_train_RMSE_std}')
print(f'RMSE Teste Std XGB: {xgb_test_RMSE_std}')

print(f'MAE Std ARIMA: {ARIMA_MAE_std}')
print(f'RMSE Treino Std ARIMA: {ARIMA_train_RMSE_std}')
print(f'RMSE Teste Std ARIMA: {ARIMA_test_RMSE_std}')

print(f'MAE Std RF: {RF_MAE_std}')
print(f'RMSE Treino Std RF: {RF_train_RMSE_std}')
print(f'RMSE Teste Std RF: {RF_test_RMSE_std}')

print(f'MAE Std Lasso: {Lasso_MAE_std}')
print(f'RMSE Treino Std Lasso: {Lasso_train_RMSE_std}')
print(f'RMSE Teste Std Lasso: {Lasso_test_RMSE_std}')

MAE Std KNN: 0.009635851133894115
RMSE Treino Std KNN: 0.007811831276038149
RMSE Teste Std KNN: 0.009635851133894115
MAE Std XGB: 0.013563907244240584
RMSE Treino Std XGB: 0.011959198841020742
RMSE Teste Std XGB: 0.013563907244240584
MAE Std ARIMA: 0.01607858672605923
RMSE Treino Std ARIMA: 0.014061900203047512
RMSE Teste Std ARIMA: 0.01607858672605923
MAE Std RF: 0.012061569837686763
RMSE Treino Std RF: 0.009147023884476578
RMSE Teste Std RF: 0.012061569837686763
MAE Std Lasso: 0.014542889348423899
RMSE Treino Std Lasso: 0.01271012116305643
RMSE Teste Std Lasso: 0.014542889348423899

In [26]:
from scipy.stats import friedmanchisquare
from scipy.stats import rankdata
import scikit_posthocs as sp

friedman_MAE = friedmanchisquare(grupo['knn_MAE'], grupo['xgb_MAE'], grupo['ARIMA_MAE'], grupo['RF_MAE'], grupo['Lasso_MAE']) 

friedman_MAE

FriedmanchisquareResult(statistic=664.5422864428385, pvalue=1.6568138429662498e-142)

In [27]:
metric_cols = ['knn_MAE', 'xgb_MAE', 'ARIMA_MAE', 'RF_MAE', 'Lasso_MAE']   
model_names = ['KNN', 'XGB', 'ARIMA', 'RF', 'Lasso']

df_sp_MAE = grupo[metric_cols]
df_sp_MAE.columns = model_names

df_sp_MAE_long = df_sp_MAE.melt(var_name='Modelo', value_name='MAE')

dunn_MAE = sp.posthoc_dunn(df_sp_MAE_long, group_col='Modelo', val_col='MAE', p_adjust='bonferroni')
dunn_MAE

          ARIMA  KNN  Lasso        RF  XGB
ARIMA  1.000000  1.0    1.0  0.118347  1.0
KNN    1.000000  1.0    1.0  1.000000  1.0
Lasso  1.000000  1.0    1.0  1.000000  1.0
RF     0.118347  1.0    1.0  1.000000  1.0
XGB    1.000000  1.0    1.0  1.000000  1.0

In [28]:
# Aplicar ranking por linha (menor MAE = melhor)
ranks_MAE = grupo[['knn_MAE', 'xgb_MAE', 'ARIMA_MAE', 'RF_MAE', 'Lasso_MAE']].apply(rankdata, axis=1)
mean_ranks_MAE = ranks_MAE.mean(axis=0)

# Exibir ranking médio
print("Rank médio da MAE dos modelos:")
for i, rank in enumerate(mean_ranks_MAE, start=1):
    print(f"Modelo {i}: {rank:.3f}")

Rank médio da MAE dos modelos:
Modelo 1: 2.885
Modelo 2: 2.979
Modelo 3: 4.410
Modelo 4: 1.766
Modelo 5: 2.960

In [29]:
friedman_RMSE_train = friedmanchisquare(grupo['knn_train_RMSE'], grupo['xgb_train_RMSE'], grupo['ARIMA_train_RMSE'], grupo['RF_train_RMSE'], grupo['Lasso_train_RMSE']) 

friedman_RMSE_train

FriedmanchisquareResult(statistic=1498.7216319592014, pvalue=0.0)

In [30]:
metric_cols = ['knn_train_RMSE', 'xgb_train_RMSE', 'ARIMA_train_RMSE', 'RF_train_RMSE', 'Lasso_train_RMSE']   
model_names = ['KNN', 'XGB', 'ARIMA', 'RF', 'Lasso']

df_sp_RMSE = grupo[metric_cols]
df_sp_RMSE.columns = model_names

df_sp_RMSE_long = df_sp_RMSE.melt(var_name='Modelo', value_name='RMSE')

dunn_RMSE = sp.posthoc_dunn(df_sp_RMSE_long, group_col='Modelo', val_col='RMSE', p_adjust='bonferroni')
dunn_RMSE

          ARIMA       KNN     Lasso        RF       XGB
ARIMA  1.000000  0.007142  0.969322  0.000307  1.000000
KNN    0.007142  1.000000  0.846776  1.000000  0.807164
Lasso  0.969322  0.846776  1.000000  0.121423  1.000000
RF     0.000307  1.000000  0.121423  1.000000  0.113947
XGB    1.000000  0.807164  1.000000  0.113947  1.000000

In [31]:
# Aplicar ranking por linha (menor MAE = melhor)r
ranks_RMSE_train = grupo[['knn_train_RMSE', 'xgb_train_RMSE', 'ARIMA_train_RMSE', 'RF_train_RMSE', 'Lasso_train_RMSE']].apply(rankdata, axis=1)
mean_ranks_RMSE_train = ranks_RMSE_train.mean(axis=0)

# Exibir ranking médio
print("Rank médio da RMSE do treino dos modelos:")
for i, rank in enumerate(mean_ranks_RMSE_train, start=1):
    print(f"Modelo {i}: {rank:.3f}")

Rank médio da RMSE do treino dos modelos:
Modelo 1: 1.624
Modelo 2: 3.845
Modelo 3: 4.938
Modelo 4: 1.752
Modelo 5: 2.841

In [32]:
rmse_final

,Empresa,RMSE_knn,RMSE_xgb,RMSE_ARIMA,RMSE_RF,RMSE_Lasso
0,3tentos,1.160052e-03,1.377042e-03,1.468946e-03,1.275987e-03,1.377050e-03
1,521 Particip,3.927909e-03,3.639417e-03,5.183695e-03,3.627222e-03,3.639415e-03
2,524 Particip,2.747847e-07,2.464912e-07,4.633692e-07,2.405112e-07,2.451595e-07
3,AES Brasil,3.397857e-03,3.989522e-03,4.064827e-03,2.910590e-03,3.989521e-03
4,AES Elpa,1.936200e-03,2.068836e-03,2.534166e-03,1.783257e-03,2.068836e-03
...,...,...,...,...,...,...
466,Yara Brasil,1.238945e-03,1.704542e-03,2.121447e-04,2.154250e-03,1.704545e-03
467,Ybyra S/A,9.074867e-05,9.302781e-05,1.117834e-04,9.267641e-05,9.302932e-05
468,Yduqs Part,2.029460e-03,2.086387e-03,2.109890e-03,1.561930e-03,2.086388e-03
469,Zain Part,3.884825e-08,2.990656e-08,6.446388e-08,4.018180e-08,3.884825e-08
470,Zamp S.A.,1.292313e-03,1.210891e-03,1.465065e-03,1.021602e-03,1.210889e-03

In [33]:
friedman_RMSE = friedmanchisquare(rmse_final['RMSE_knn'], rmse_final['RMSE_xgb'], rmse_final['RMSE_ARIMA'], rmse_final['RMSE_RF'], rmse_final['RMSE_Lasso']) 

friedman_RMSE

FriedmanchisquareResult(statistic=729.9534686072452, pvalue=1.1378152398163201e-156)

In [34]:
# Aplicar ranking por linha (menor MAE = melhor)r
ranks_RMSE = rmse_final[['RMSE_knn', 'RMSE_xgb', 'RMSE_ARIMA', 'RMSE_RF', 'RMSE_Lasso']].apply(rankdata, axis=1)
mean_ranks_RMSE = ranks_RMSE.mean(axis=0)

# Exibir ranking médio
print("Rank médio da RMSE geral dos modelos:")
for i, rank in enumerate(mean_ranks_RMSE, start=1):
    print(f"Modelo {i}: {rank:.3f}")

Rank médio da RMSE geral dos modelos:
Modelo 1: 2.886
Modelo 2: 2.945
Modelo 3: 4.510
Modelo 4: 1.747
Modelo 5: 2.912

In [35]:
rmse_final

,Empresa,RMSE_knn,RMSE_xgb,RMSE_ARIMA,RMSE_RF,RMSE_Lasso
0,3tentos,1.160052e-03,1.377042e-03,1.468946e-03,1.275987e-03,1.377050e-03
1,521 Particip,3.927909e-03,3.639417e-03,5.183695e-03,3.627222e-03,3.639415e-03
2,524 Particip,2.747847e-07,2.464912e-07,4.633692e-07,2.405112e-07,2.451595e-07
3,AES Brasil,3.397857e-03,3.989522e-03,4.064827e-03,2.910590e-03,3.989521e-03
4,AES Elpa,1.936200e-03,2.068836e-03,2.534166e-03,1.783257e-03,2.068836e-03
...,...,...,...,...,...,...
466,Yara Brasil,1.238945e-03,1.704542e-03,2.121447e-04,2.154250e-03,1.704545e-03
467,Ybyra S/A,9.074867e-05,9.302781e-05,1.117834e-04,9.267641e-05,9.302932e-05
468,Yduqs Part,2.029460e-03,2.086387e-03,2.109890e-03,1.561930e-03,2.086388e-03
469,Zain Part,3.884825e-08,2.990656e-08,6.446388e-08,4.018180e-08,3.884825e-08
470,Zamp S.A.,1.292313e-03,1.210891e-03,1.465065e-03,1.021602e-03,1.210889e-03