In [41]:
import pandas as pd
import numpy as np

df_knn = pd.read_csv('KNN_resultados_FCLF.csv')
df_xgb = pd.read_csv('XGBoost_resultados_FCLF.csv')
df_ARIMA = pd.read_csv('ARIMA_resultados.csv')
df_RF = pd.read_csv('RF_resultados_FCLF.csv')
df_Lasso = pd.read_csv('Lasso_resultados_FCLF.csv')

In [42]:
df_knn = df_knn.drop(columns=["Unnamed: 0", "Overfitting?", "Underfitting?"])
df_knn = df_knn.rename(columns={
    'Real':'Valores Reais',
    'Previsto':'knn_Previsto',
    'Erro Absoluto':'knn_MAE',
    'Train RMSE':'knn_train_RMSE',
    'Test RMSE':'knn_test_RMSE'
        })

In [43]:
df_xgb = df_xgb.drop(columns=["Unnamed: 0", "Overfitting?", "Underfitting?"])
df_xgb = df_xgb.rename(columns={
    'Real':'Valores Reais',
    'Previsto':'xgb_Previsto',
    'Erro Absoluto':'xgb_MAE',
    'Train RMSE':'xgb_train_RMSE',
    'Test RMSE':'xgb_test_RMSE'
        })

In [44]:
df_ARIMA = df_ARIMA.drop(columns=["Unnamed: 0", "Overfitting?", "Underfitting?"])
df_ARIMA = df_ARIMA.rename(columns={
    'Real':'Valores Reais',
    'Previsto':'ARIMA_Previsto',
    'Erro Absoluto':'ARIMA_MAE',
    'Train RMSE':'ARIMA_train_RMSE',
    'Test RMSE':'ARIMA_test_RMSE'
        })

In [45]:
df_RF = df_RF.drop(columns=["Unnamed: 0", "Overfitting?", "Underfitting?"])
df_RF = df_RF.rename(columns={
    'Real':'Valores Reais',
    'Previsto':'RF_Previsto',
    'Erro Absoluto':'RF_MAE',
    'Train RMSE':'RF_train_RMSE',
    'Test RMSE':'RF_test_RMSE'
        })

In [46]:
df_Lasso = df_Lasso.drop(columns=["Unnamed: 0", "Overfitting?", "Underfitting?"])
df_Lasso = df_Lasso.rename(columns={
    'Real':'Valores Reais',
    'Previsto':'Lasso_Previsto',
    'Erro Absoluto':'Lasso_MAE',
    'Train RMSE':'Lasso_train_RMSE',
    'Test RMSE':'Lasso_test_RMSE'
        })

In [47]:
df = pd.merge(df_knn, df_xgb, on=['Empresa', 'Data', 'Valores Reais'], how='right')
df = pd.merge(df, df_ARIMA, on=['Empresa', 'Data', 'Valores Reais'], how='right')
df = pd.merge(df, df_RF, on=['Empresa', 'Data', 'Valores Reais'], how='right')
df = pd.merge(df, df_Lasso, on=['Empresa', 'Data', 'Valores Reais'], how='right')
df

,Empresa,Data,Valores Reais,knn_Previsto,knn_MAE,knn_train_RMSE,knn_test_RMSE,Erro,xgb_Previsto,xgb_MAE,...,ARIMA_train_RMSE,ARIMA_test_RMSE,RF_Previsto,RF_MAE,RF_train_RMSE,RF_test_RMSE,Lasso_Previsto,Lasso_MAE,Lasso_train_RMSE,Lasso_test_RMSE
0,3tentos,2022-10-01,0.806510,0.806467,0.000042,0.000057,0.000042,0.000042,0.806467,0.000042,...,0.000109,0.000078,0.806462,0.000048,0.000058,0.000048,0.806467,0.000042,0.000057,0.000042
1,3tentos,2023-01-01,0.806410,0.806486,0.000075,0.000055,0.000075,-0.000075,0.806476,0.000065,...,0.000072,0.000054,0.806479,0.000068,0.000054,0.000068,0.806476,0.000065,0.000054,0.000065
2,3tentos,2023-04-01,0.806508,0.806479,0.000028,0.000057,0.000028,0.000028,0.806465,0.000043,...,0.000065,0.000026,0.806467,0.000041,0.000055,0.000041,0.806465,0.000043,0.000055,0.000043
3,3tentos,2023-07-01,0.806415,0.806479,0.000064,0.000053,0.000064,-0.000064,0.806471,0.000056,...,0.000066,0.000023,0.806473,0.000057,0.000053,0.000057,0.806471,0.000056,0.000053,0.000056
4,3tentos,2023-10-01,0.806359,0.806441,0.000082,0.000051,0.000082,-0.000082,0.806464,0.000105,...,0.000060,0.000129,0.806465,0.000106,0.000053,0.000106,0.806464,0.000105,0.000053,0.000105
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7921,Zamp S.A.,2023-07-01,0.806388,0.806445,0.000057,0.000336,0.000057,-0.000057,0.806402,0.000014,...,0.000511,0.000056,0.806403,0.000014,0.000283,0.000014,0.806402,0.000014,0.000402,0.000014
7922,Zamp S.A.,2023-10-01,0.806579,0.806437,0.000143,0.000329,0.000143,0.000143,0.806401,0.000178,...,0.000500,0.000145,0.806385,0.000194,0.000283,0.000194,0.806401,0.000178,0.000393,0.000178
7923,Zamp S.A.,2024-01-01,0.806390,0.806436,0.000046,0.000323,0.000046,-0.000046,0.806408,0.000019,...,0.000491,0.000091,0.806346,0.000043,0.000275,0.000043,0.806408,0.000019,0.000387,0.000019
7924,Zamp S.A.,2024-04-01,0.806425,0.806413,0.000011,0.000317,0.000011,0.000011,0.806408,0.000017,...,0.000481,0.000056,0.806431,0.000007,0.000270,0.000007,0.806408,0.000017,0.000379,0.000017
7925,Zamp S.A.,2024-07-01,0.806377,0.806402,0.000025,0.000311,0.000025,-0.000025,0.806408,0.000032,...,0.000472,0.000042,0.806393,0.000016,0.000259,0.000016,0.806408,0.000032,0.000372,0.000032

In [48]:
from sklearn.metrics import mean_squared_error
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

# Função para calcular RMSE
def calcular_rmse_knn(df):
    return np.sqrt(mean_squared_error(df['Valores Reais'], df['knn_Previsto']))

# Aplicar por grupo (por empresa)
rmse_por_empresa_knn = df.groupby('Empresa').apply(calcular_rmse_knn).reset_index()
rmse_por_empresa_knn.columns = ['Empresa', 'RMSE_knn']

In [49]:
# Função para calcular RMSE
def calcular_rmse_xgb(df):
    return np.sqrt(mean_squared_error(df['Valores Reais'], df['xgb_Previsto']))

# Aplicar por grupo (por empresa)
rmse_por_empresa_xgb = df.groupby('Empresa').apply(calcular_rmse_xgb).reset_index()
rmse_por_empresa_xgb.columns = ['Empresa', 'RMSE_xgb']

In [50]:
# Função para calcular RMSE
def calcular_rmse_ARIMA(df):
    return np.sqrt(mean_squared_error(df['Valores Reais'], df['ARIMA_Previsto']))

# Aplicar por grupo (por empresa)
rmse_por_empresa_ARIMA = df.groupby('Empresa').apply(calcular_rmse_ARIMA).reset_index()
rmse_por_empresa_ARIMA.columns = ['Empresa', 'RMSE_ARIMA']

In [51]:
def calcular_rmse_RF(df):
    return np.sqrt(mean_squared_error(df['Valores Reais'], df['RF_Previsto']))

# Aplicar por grupo (por empresa)
rmse_por_empresa_RF = df.groupby('Empresa').apply(calcular_rmse_RF).reset_index()
rmse_por_empresa_RF.columns = ['Empresa', 'RMSE_RF']

In [52]:
def calcular_rmse_Lasso(df):
    return np.sqrt(mean_squared_error(df['Valores Reais'], df['Lasso_Previsto']))

# Aplicar por grupo (por empresa)
rmse_por_empresa_Lasso = df.groupby('Empresa').apply(calcular_rmse_Lasso).reset_index()
rmse_por_empresa_Lasso.columns = ['Empresa', 'RMSE_Lasso']

In [53]:
rmse_final = pd.merge(rmse_por_empresa_knn, rmse_por_empresa_xgb, on=['Empresa'], how='right')
rmse_final = pd.merge(rmse_final, rmse_por_empresa_ARIMA, on=['Empresa'], how='right')
rmse_final = pd.merge(rmse_final, rmse_por_empresa_RF, on=['Empresa'], how='right')
rmse_final = pd.merge(rmse_final, rmse_por_empresa_Lasso, on=['Empresa'], how='right')

empresa_maior_rmse_knn = rmse_final.loc[rmse_final['RMSE_knn'].idxmax()]
empresa_menor_rmse_knn = rmse_final.loc[rmse_final['RMSE_knn'].idxmin()]

# Maior e menor RMSE para o XGB
empresa_maior_rmse_xgb = rmse_final.loc[rmse_final['RMSE_xgb'].idxmax()]
empresa_menor_rmse_xgb = rmse_final.loc[rmse_final['RMSE_xgb'].idxmin()]

# Maior e menor RMSE para o ARIMA
empresa_maior_rmse_ARIMA = rmse_final.loc[rmse_final['RMSE_ARIMA'].idxmax()]
empresa_menor_rmse_ARIMA = rmse_final.loc[rmse_final['RMSE_ARIMA'].idxmin()]

# Maior e menor RMSE para o RF
empresa_maior_rmse_RF = rmse_final.loc[rmse_final['RMSE_RF'].idxmax()]
empresa_menor_rmse_RF = rmse_final.loc[rmse_final['RMSE_RF'].idxmin()]

# Maior e menor RMSE para o Lasso
empresa_maior_rmse_Lasso = rmse_final.loc[rmse_final['RMSE_Lasso'].idxmax()]
empresa_menor_rmse_Lasso = rmse_final.loc[rmse_final['RMSE_Lasso'].idxmin()]

print("Maior RMSE KNN:", empresa_maior_rmse_knn)
print("Menor RMSE KNN:", empresa_menor_rmse_knn)

print("Maior RMSE XGB:", empresa_maior_rmse_xgb)
print("Menor RMSE XGB:", empresa_menor_rmse_xgb)

print("Maior RMSE ARIMA:", empresa_maior_rmse_ARIMA)
print("Menor RMSE ARIMA:", empresa_menor_rmse_ARIMA)

print("Maior RMSE RF:", empresa_maior_rmse_RF)
print("Menor RMSE RF:", empresa_menor_rmse_RF)

print("Maior RMSE Lasso:", empresa_maior_rmse_Lasso)
print("Menor RMSE Lasso:", empresa_menor_rmse_Lasso)

Maior RMSE KNN: Empresa       Sequoia Log
RMSE_knn         0.232791
RMSE_xgb         0.242941
RMSE_ARIMA       0.352581
RMSE_RF          0.242316
RMSE_Lasso       0.242941
Name: 228, dtype: object
Menor RMSE KNN: Empresa       Westwing
RMSE_knn      0.000017
RMSE_xgb      0.000013
RMSE_ARIMA    0.000031
RMSE_RF       0.000012
RMSE_Lasso    0.000013
Name: 273, dtype: object
Maior RMSE XGB: Empresa       Sequoia Log
RMSE_knn         0.232791
RMSE_xgb         0.242941
RMSE_ARIMA       0.352581
RMSE_RF          0.242316
RMSE_Lasso       0.242941
Name: 228, dtype: object
Menor RMSE XGB: Empresa       Westwing
RMSE_knn      0.000017
RMSE_xgb      0.000013
RMSE_ARIMA    0.000031
RMSE_RF       0.000012
RMSE_Lasso    0.000013
Name: 273, dtype: object
Maior RMSE ARIMA: Empresa       Sequoia Log
RMSE_knn         0.232791
RMSE_xgb         0.242941
RMSE_ARIMA       0.352581
RMSE_RF          0.242316
RMSE_Lasso       0.242941
Name: 228, dtype: object
Menor RMSE ARIMA: Empresa       Kora Saude
RMSE_knn        0.000038
RMSE_xgb        0.000057
RMSE_ARIMA      0.000029
RMSE_RF         0.000059
RMSE_Lasso      0.000057
Name: 142, dtype: object
Maior RMSE RF: Empresa       Sequoia Log
RMSE_knn         0.232791
RMSE_xgb         0.242941
RMSE_ARIMA       0.352581
RMSE_RF          0.242316
RMSE_Lasso       0.242941
Name: 228, dtype: object
Menor RMSE RF: Empresa       Westwing
RMSE_knn      0.000017
RMSE_xgb      0.000013
RMSE_ARIMA    0.000031
RMSE_RF       0.000012
RMSE_Lasso    0.000013
Name: 273, dtype: object
Maior RMSE Lasso: Empresa       Sequoia Log
RMSE_knn         0.232791
RMSE_xgb         0.242941
RMSE_ARIMA       0.352581
RMSE_RF          0.242316
RMSE_Lasso       0.242941
Name: 228, dtype: object
Menor RMSE Lasso: Empresa       Westwing
RMSE_knn      0.000017
RMSE_xgb      0.000013
RMSE_ARIMA    0.000031
RMSE_RF       0.000012
RMSE_Lasso    0.000013
Name: 273, dtype: object

In [54]:
rmse_final.to_csv("rmse_final_FCLF.csv")

In [55]:
grupo = df.groupby('Empresa')[['knn_MAE', 'knn_train_RMSE', 'knn_test_RMSE', 'xgb_MAE', 'xgb_train_RMSE', 'xgb_test_RMSE', 'ARIMA_MAE', 'ARIMA_train_RMSE', 'ARIMA_test_RMSE', 'RF_MAE', 'RF_train_RMSE', 'RF_test_RMSE', 'Lasso_MAE', 'Lasso_train_RMSE', 'Lasso_test_RMSE']].mean().reset_index()
grupo #media do MAE, media do RMSE de treino e media do RMSE teste por modelo

,Empresa,knn_MAE,knn_train_RMSE,knn_test_RMSE,xgb_MAE,xgb_train_RMSE,xgb_test_RMSE,ARIMA_MAE,ARIMA_train_RMSE,ARIMA_test_RMSE,RF_MAE,RF_train_RMSE,RF_test_RMSE,Lasso_MAE,Lasso_train_RMSE,Lasso_test_RMSE
0,3tentos,0.000257,0.000060,0.000257,0.000249,0.000066,0.000249,0.000330,0.000098,0.000330,0.000249,0.000065,0.000249,0.000249,0.000066,0.000249
1,Aco Altona,0.002494,0.023240,0.002494,0.014404,0.034042,0.014404,0.000488,0.027769,0.000488,0.009778,0.028124,0.009778,0.014404,0.034042,0.014404
2,Aeris,0.000103,0.000069,0.000103,0.000099,0.000073,0.000099,0.000190,0.000091,0.000190,0.000099,0.000071,0.000099,0.000099,0.000073,0.000099
3,Afluente T,0.000134,0.000100,0.000134,0.000114,0.000115,0.000114,0.000166,0.000134,0.000166,0.000107,0.000084,0.000107,0.000114,0.000115,0.000114
4,Agrogalaxy,0.000414,0.000300,0.000414,0.000525,0.000375,0.000525,0.000829,0.000544,0.000829,0.000577,0.000379,0.000577,0.000525,0.000375,0.000525
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
275,Wilson Sons,0.000138,0.000134,0.000138,0.000098,0.000171,0.000098,0.000179,0.000235,0.000179,0.000090,0.000135,0.000090,0.000098,0.000171,0.000098
276,Wiz Co,0.000382,0.000405,0.000382,0.000375,0.000473,0.000375,0.000561,0.000592,0.000561,0.000358,0.000436,0.000358,0.000375,0.000473,0.000375
277,Wlm Ind Com,0.000201,0.000214,0.000201,0.000168,0.000275,0.000168,0.000349,0.000331,0.000349,0.000179,0.000200,0.000179,0.000168,0.000275,0.000168
278,Yduqs Part,0.000080,0.000091,0.000080,0.000070,0.000105,0.000070,0.000080,0.000128,0.000080,0.000067,0.000075,0.000067,0.000070,0.000105,0.000070
279,Zamp S.A.,0.000252,0.000405,0.000252,0.000206,0.000465,0.000206,0.000417,0.000641,0.000417,0.000208,0.000400,0.000208,0.000206,0.000465,0.000206

In [56]:
grupo.to_csv("friedman_data_FCLF.csv")

In [57]:
knn_MAE_media = df['knn_MAE'].mean()
knn_train_RMSE_media = df['knn_train_RMSE'].mean()
knn_test_RMSE_media = df['knn_test_RMSE'].mean()

xgb_MAE_media = df['xgb_MAE'].mean()
xgb_train_RMSE_media = df['xgb_train_RMSE'].mean()
xgb_test_RMSE_media = df['xgb_test_RMSE'].mean()

ARIMA_MAE_media = df['ARIMA_MAE'].mean()
ARIMA_train_RMSE_media = df['ARIMA_train_RMSE'].mean()
ARIMA_test_RMSE_media = df['ARIMA_test_RMSE'].mean()

RF_MAE_media = df['RF_MAE'].mean()
RF_train_RMSE_media = df['RF_train_RMSE'].mean()
RF_test_RMSE_media = df['RF_test_RMSE'].mean()

Lasso_MAE_media = df['Lasso_MAE'].mean()
Lasso_train_RMSE_media = df['Lasso_train_RMSE'].mean()
Lasso_test_RMSE_media = df['Lasso_test_RMSE'].mean()


print(f'MAE Médio KNN: {knn_MAE_media}') #é diferente do MAE geral do modelo pois as médias de cada empresas possuem ns diferentes (datasets com observações diferentes)
print(f'RMSE Treino Médio KNN: {knn_train_RMSE_media}')
print(f'RMSE Teste Médio KNN: {knn_test_RMSE_media}')

print(f'MAE Médio XGB: {xgb_MAE_media}')
print(f'RMSE Treino Médio XGB: {xgb_train_RMSE_media}')
print(f'RMSE Teste Médio XGB: {xgb_test_RMSE_media}')

print(f'MAE Médio ARIMA: {ARIMA_MAE_media}')
print(f'RMSE Treino Médio ARIMA: {ARIMA_train_RMSE_media}')
print(f'RMSE Teste Médio ARIMA: {ARIMA_test_RMSE_media}')

print(f'MAE Médio RF: {RF_MAE_media}')
print(f'RMSE Treino Médio RF: {RF_train_RMSE_media}')
print(f'RMSE Teste Médio RF: {RF_test_RMSE_media}')

print(f'MAE Médio Lasso: {Lasso_MAE_media}')
print(f'RMSE Treino Médio RF: {Lasso_train_RMSE_media}')
print(f'RMSE Teste Médio RF: {Lasso_test_RMSE_media}')

MAE Médio KNN: 0.0004467842254082051
RMSE Treino Médio KNN: 0.0007652324849167832
RMSE Teste Médio KNN: 0.0004467842254082051
MAE Médio XGB: 0.0006497033660804746
RMSE Treino Médio XGB: 0.0009964588547402313
RMSE Teste Médio XGB: 0.0006497033660804746
MAE Médio ARIMA: 0.0009591789924764676
RMSE Treino Médio ARIMA: 0.0010779762579455883
RMSE Teste Médio ARIMA: 0.0009591789924764676
MAE Médio RF: 0.0006309394593543217
RMSE Treino Médio RF: 0.000860483361297639
RMSE Teste Médio RF: 0.0006309394593543217
MAE Médio Lasso: 0.0006497033652271422
RMSE Treino Médio RF: 0.0009964588533755453
RMSE Teste Médio RF: 0.0006497033652271422

In [58]:
knn_MAE_std = df['knn_MAE'].std()
knn_train_RMSE_std = df['knn_train_RMSE'].std()
knn_test_RMSE_std = df['knn_test_RMSE'].std()

xgb_MAE_std = df['xgb_MAE'].std()
xgb_train_RMSE_std = df['xgb_train_RMSE'].std()
xgb_test_RMSE_std = df['xgb_test_RMSE'].std()

ARIMA_MAE_std = df['ARIMA_MAE'].std()
ARIMA_train_RMSE_std = df['ARIMA_train_RMSE'].std()
ARIMA_test_RMSE_std = df['ARIMA_test_RMSE'].std()

RF_MAE_std = df['RF_MAE'].std()
RF_train_RMSE_std = df['RF_train_RMSE'].std()
RF_test_RMSE_std = df['RF_test_RMSE'].std()

Lasso_MAE_std = df['Lasso_MAE'].std()
Lasso_train_RMSE_std = df['Lasso_train_RMSE'].std()
Lasso_test_RMSE_std = df['Lasso_test_RMSE'].std()

print(f'MAE Std KNN: {knn_MAE_std}') #é diferente do MAE geral do modelo pois as médias de cada empresas possuem ns diferentes (datasets com observações diferentes)
print(f'RMSE Treino Std KNN: {knn_train_RMSE_std}')
print(f'RMSE Teste Std KNN: {knn_test_RMSE_std}')

print(f'MAE Std XGB: {xgb_MAE_std}')
print(f'RMSE Treino Std XGB: {xgb_train_RMSE_std}')
print(f'RMSE Teste Std XGB: {xgb_test_RMSE_std}')

print(f'MAE Std ARIMA: {ARIMA_MAE_std}')
print(f'RMSE Treino Std ARIMA: {ARIMA_train_RMSE_std}')
print(f'RMSE Teste Std ARIMA: {ARIMA_test_RMSE_std}')

print(f'MAE Std RF: {RF_MAE_std}')
print(f'RMSE Treino Std RF: {RF_train_RMSE_std}')
print(f'RMSE Teste Std RF: {RF_test_RMSE_std}')

print(f'MAE Std Lasso: {Lasso_MAE_std}')
print(f'RMSE Treino Std Lasso: {Lasso_train_RMSE_std}')
print(f'RMSE Teste Std Lasso: {Lasso_test_RMSE_std}')

MAE Std KNN: 0.010566846182002286
RMSE Treino Std KNN: 0.006777590654072456
RMSE Teste Std KNN: 0.010566846182002286
MAE Std XGB: 0.010966773288451288
RMSE Treino Std XGB: 0.008643585416659359
RMSE Teste Std XGB: 0.010966773288451288
MAE Std ARIMA: 0.0157919872807795
RMSE Treino Std ARIMA: 0.009625642724322755
RMSE Teste Std ARIMA: 0.0157919872807795
MAE Std RF: 0.010972593923024333
RMSE Treino Std RF: 0.008331303650135903
RMSE Teste Std RF: 0.010972593923024333
MAE Std Lasso: 0.010966773109802732
RMSE Treino Std Lasso: 0.008643585416797727
RMSE Teste Std Lasso: 0.010966773109802732

In [59]:
from scipy.stats import friedmanchisquare
from scipy.stats import rankdata
import scikit_posthocs as sp

friedman_MAE = friedmanchisquare(grupo['knn_MAE'], grupo['xgb_MAE'], grupo['ARIMA_MAE'], grupo['RF_MAE'], grupo['Lasso_MAE']) 

friedman_MAE

FriedmanchisquareResult(statistic=433.3261879242589, pvalue=1.7466209229063386e-92)

In [60]:
metric_cols = ['knn_MAE', 'xgb_MAE', 'ARIMA_MAE', 'RF_MAE', 'Lasso_MAE']   
model_names = ['KNN', 'XGB', 'ARIMA', 'RF', 'Lasso']

df_sp_MAE = grupo[metric_cols]
df_sp_MAE.columns = model_names

df_sp_MAE_long = df_sp_MAE.melt(var_name='Modelo', value_name='MAE')

dunn_MAE = sp.posthoc_dunn(df_sp_MAE_long, group_col='Modelo', val_col='MAE', p_adjust='bonferroni')
dunn_MAE

          ARIMA       KNN     Lasso        RF       XGB
ARIMA  1.000000  0.001673  0.000096  0.000009  0.000095
KNN    0.001673  1.000000  1.000000  1.000000  1.000000
Lasso  0.000096  1.000000  1.000000  1.000000  1.000000
RF     0.000009  1.000000  1.000000  1.000000  1.000000
XGB    0.000095  1.000000  1.000000  1.000000  1.000000

In [61]:
# Aplicar ranking por linha (menor MAE = melhor)
ranks_MAE = grupo[['knn_MAE', 'xgb_MAE', 'ARIMA_MAE', 'RF_MAE', 'Lasso_MAE']].apply(rankdata, axis=1)
mean_ranks_MAE = ranks_MAE.mean(axis=0)

# Exibir ranking médio
print("Rank médio da MAE dos modelos:")
for i, rank in enumerate(mean_ranks_MAE, start=1):
    print(f"Modelo {i}: {rank:.3f}")

Rank médio da MAE dos modelos:
Modelo 1: 2.971
Modelo 2: 2.568
Modelo 3: 4.682
Modelo 4: 2.161
Modelo 5: 2.618

In [62]:
friedman_RMSE_train = friedmanchisquare(grupo['knn_train_RMSE'], grupo['xgb_train_RMSE'], grupo['ARIMA_train_RMSE'], grupo['RF_train_RMSE'], grupo['Lasso_train_RMSE']) 

friedman_RMSE_train

FriedmanchisquareResult(statistic=948.861736334405, pvalue=4.309027701373682e-204)

In [63]:
metric_cols = ['knn_train_RMSE', 'xgb_train_RMSE', 'ARIMA_train_RMSE', 'RF_train_RMSE', 'Lasso_train_RMSE']   
model_names = ['KNN', 'XGB', 'ARIMA', 'RF', 'Lasso']

df_sp_RMSE = grupo[metric_cols]
df_sp_RMSE.columns = model_names

df_sp_RMSE_long = df_sp_RMSE.melt(var_name='Modelo', value_name='RMSE')

dunn_RMSE = sp.posthoc_dunn(df_sp_RMSE_long, group_col='Modelo', val_col='RMSE', p_adjust='bonferroni')
dunn_RMSE

          ARIMA       KNN     Lasso        RF       XGB
ARIMA  1.000000  0.000037  0.111243  0.000014  0.120937
KNN    0.000037  1.000000  0.368959  1.000000  0.343206
Lasso  0.111243  0.368959  1.000000  0.220818  1.000000
RF     0.000014  1.000000  0.220818  1.000000  0.204314
XGB    0.120937  0.343206  1.000000  0.204314  1.000000

In [64]:
# Aplicar ranking por linha (menor MAE = melhor)r
ranks_RMSE_train = grupo[['knn_train_RMSE', 'xgb_train_RMSE', 'ARIMA_train_RMSE', 'RF_train_RMSE', 'Lasso_train_RMSE']].apply(rankdata, axis=1)
mean_ranks_RMSE_train = ranks_RMSE_train.mean(axis=0)

# Exibir ranking médio
print("Rank médio da RMSE do treino dos modelos:")
for i, rank in enumerate(mean_ranks_RMSE_train, start=1):
    print(f"Modelo {i}: {rank:.3f}")

Rank médio da RMSE do treino dos modelos:
Modelo 1: 1.500
Modelo 2: 3.950
Modelo 3: 4.904
Modelo 4: 1.700
Modelo 5: 2.946

In [65]:
rmse_final

         Empresa  RMSE_knn  RMSE_xgb  RMSE_ARIMA   RMSE_RF  RMSE_Lasso
0        3tentos  0.000546  0.000534    0.000652  0.000531    0.000534
1     Aco Altona  0.010092  0.018245    0.001527  0.016908    0.018245
2          Aeris  0.000156  0.000165    0.000251  0.000165    0.000165
3     Afluente T  0.000261  0.000246    0.000305  0.000240    0.000246
4     Agrogalaxy  0.001086  0.001104    0.001546  0.001122    0.001104
..           ...       ...       ...         ...       ...         ...
275  Wilson Sons  0.000221  0.000187    0.000293  0.000183    0.000187
276       Wiz Co  0.000680  0.000671    0.000837  0.000667    0.000671
277  Wlm Ind Com  0.000410  0.000400    0.000710  0.000404    0.000400
278   Yduqs Part  0.000116  0.000107    0.000116  0.000101    0.000107
279    Zamp S.A.  0.000465  0.000429    0.000848  0.000432    0.000429

[280 rows x 6 columns]

In [66]:
friedman_RMSE = friedmanchisquare(rmse_final['RMSE_knn'], rmse_final['RMSE_xgb'], rmse_final['RMSE_ARIMA'], rmse_final['RMSE_RF'], rmse_final['RMSE_Lasso']) 

friedman_RMSE

FriedmanchisquareResult(statistic=474.43229724901715, pvalue=2.2662448642748787e-101)

In [67]:
# Aplicar ranking por linha (menor MAE = melhor)r
ranks_RMSE = rmse_final[['RMSE_knn', 'RMSE_xgb', 'RMSE_ARIMA', 'RMSE_RF', 'RMSE_Lasso']].apply(rankdata, axis=1)
mean_ranks_RMSE = ranks_RMSE.mean(axis=0)

# Exibir ranking médio
print("Rank médio da RMSE do treino dos modelos:")
for i, rank in enumerate(mean_ranks_RMSE, start=1):
    print(f"Modelo {i}: {rank:.3f}")

Rank médio da RMSE do treino dos modelos:
Modelo 1: 2.836
Modelo 2: 2.721
Modelo 3: 4.721
Modelo 4: 1.943
Modelo 5: 2.779

In [68]:
rmse_final

         Empresa  RMSE_knn  RMSE_xgb  RMSE_ARIMA   RMSE_RF  RMSE_Lasso
0        3tentos  0.000546  0.000534    0.000652  0.000531    0.000534
1     Aco Altona  0.010092  0.018245    0.001527  0.016908    0.018245
2          Aeris  0.000156  0.000165    0.000251  0.000165    0.000165
3     Afluente T  0.000261  0.000246    0.000305  0.000240    0.000246
4     Agrogalaxy  0.001086  0.001104    0.001546  0.001122    0.001104
..           ...       ...       ...         ...       ...         ...
275  Wilson Sons  0.000221  0.000187    0.000293  0.000183    0.000187
276       Wiz Co  0.000680  0.000671    0.000837  0.000667    0.000671
277  Wlm Ind Com  0.000410  0.000400    0.000710  0.000404    0.000400
278   Yduqs Part  0.000116  0.000107    0.000116  0.000101    0.000107
279    Zamp S.A.  0.000465  0.000429    0.000848  0.000432    0.000429

[280 rows x 6 columns]